# Generated by Django 5.1.7 on 2025-05-14 01:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPlaylists',
            fields=[
                ('admin_playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('total_songs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylists',
            fields=[
                ('user_playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=100)),
                ('playlist_number', models.IntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('total_songs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('background', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['artist_name'], name='api_artists_artist__4008d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=100)),
                ('album_title', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=255, null=True)),
                ('total_songs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.artists')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['genre_name'], name='api_genres_genre_n_ed6dd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('audio_url', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.BinaryField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image_file', models.BinaryField(blank=True, null=True)),
                ('vinyl_background', models.CharField(blank=True, max_length=255, null=True)),
                ('listeners', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('explicit', models.BooleanField(default=False)),
                ('lyrics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='api.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.artists')),
            ],
        ),
        migrations.CreateModel(
            name='SongGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.genres')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='api.songs')),
            ],
        ),
        migrations.CreateModel(
            name='AdminPlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_playlist_songs', to='api.adminplaylists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_playlists', to='api.songs')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist_songs', to='api.userplaylists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to='api.songs')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='api_users_usernam_75711e_idx'), models.Index(fields=['email'], name='api_users_email_19221f_idx')],
            },
        ),
        migrations.AddField(
            model_name='userplaylists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='api.users'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='api.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='api.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.BinaryField(blank=True, null=True)),
                ('listeners', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('explicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='api.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.artists')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='api.songs')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_history', to='api.userplaylists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='api.users')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='api.video')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.albums')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.users')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.genres')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='api.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='albums',
            index=models.Index(fields=['artist'], name='api_albums_artist__027a63_idx'),
        ),
        migrations.AddIndex(
            model_name='songs',
            index=models.Index(fields=['artist'], name='api_songs_artist__6fcfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='songs',
            index=models.Index(fields=['album'], name='api_songs_album_i_e8d07c_idx'),
        ),
        migrations.AddIndex(
            model_name='songs',
            index=models.Index(fields=['listeners'], name='api_songs_listene_ff716f_idx'),
        ),
        migrations.AddIndex(
            model_name='songs',
            index=models.Index(fields=['total_likes'], name='api_songs_total_l_f6d24d_idx'),
        ),
        migrations.AddConstraint(
            model_name='songgenres',
            constraint=models.UniqueConstraint(fields=('song', 'genre'), name='unique_song_genre'),
        ),
        migrations.AddConstraint(
            model_name='adminplaylistsongs',
            constraint=models.UniqueConstraint(fields=('playlist', 'song'), name='unique_admin_playlist_song'),
        ),
        migrations.AddConstraint(
            model_name='userplaylistsongs',
            constraint=models.UniqueConstraint(fields=('playlist', 'song'), name='unique_user_playlist_song'),
        ),
        migrations.AddConstraint(
            model_name='userplaylists',
            constraint=models.UniqueConstraint(fields=('user', 'playlist_number'), name='unique_user_playlist_number'),
        ),
        migrations.AddConstraint(
            model_name='userplaylists',
            constraint=models.UniqueConstraint(fields=('user', 'playlist_name'), name='unique_user_playlist_name'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='api_message_sender__7d2c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='api_message_receive_d51b26_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_at'], name='api_message_sent_at_a15a80_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['sender'], name='api_friendr_sender__58ca08_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['receiver'], name='api_friendr_receive_765be7_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['status'], name='api_friendr_status_9ae5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['created_at'], name='api_friendr_created_6d2970_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver'), name='unique_friend_request'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['artist'], name='api_video_artist__42ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['album'], name='api_video_album_i_072340_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['listeners'], name='api_video_listene_7cb7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['total_likes'], name='api_video_total_l_7ef8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user'], name='api_listeni_user_id_29d506_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['song'], name='api_listeni_song_id_4f7234_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['video'], name='api_listeni_video_i_e49a38_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['listened_at'], name='api_listeni_listene_29c110_idx'),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(condition=models.Q(('song__isnull', False)), fields=('user', 'song'), name='unique_user_song_like'),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(condition=models.Q(('video__isnull', False)), fields=('user', 'video'), name='unique_user_video_like'),
        ),
        migrations.AddConstraint(
            model_name='videogenres',
            constraint=models.UniqueConstraint(fields=('video', 'genre'), name='unique_video_genre'),
        ),
    ]
