from django.urls import path
from .views import (
    AlbumListView, AlbumDetailView, ArtistListView, ArtistDetailView,
    SongListView, SongDetailView, SongStreamView, GenreListView, GenreDetailView,
    UserPlaylistListView, UserPlaylistDetailView, UserPlaylistSongsView,
    TopSongsView, SearchView, UserListView, UserDetailView,
    ListeningHistoryView, LoginView, SignupView, GoogleAuthView,
    GoogleCallbackView, UserLikesView, UserListeningHistoryView, RandomSongsView,
    ImportSongsView, VideoListView, VideoDetailView, VideoStreamView,
    AdminPlaylistListView, AdminPlaylistDetailView, MessageListView, MessageReadView,
    FriendRequestListView, FriendRequestDetailView, FriendRequestAcceptView, 
    FriendRequestRejectView, FriendsListView, VerifyPasswordView
)

urlpatterns = [
    path('albums/', AlbumListView.as_view(), name='album-list'),
    path('albums/<int:album_id>/', AlbumDetailView.as_view(), name='album-detail'),
    path('artists/', ArtistListView.as_view(), name='artist-list'),
    path('artists/<int:artist_id>/', ArtistDetailView.as_view(), name='artist-detail'),
    path('songs/', SongListView.as_view(), name='song-list'),
    path('songs/<int:song_id>/', SongDetailView.as_view(), name='song-detail'),
    path('songs/<int:song_id>/stream/', SongStreamView.as_view(), name='song-stream'),
    path('videos/', VideoListView.as_view(), name='video-list'),
    path('videos/<int:video_id>/', VideoDetailView.as_view(), name='video-detail'),
    path('videos/<int:video_id>/stream/', VideoStreamView.as_view(), name='video-stream'),
    path('genres/', GenreListView.as_view(), name='genre-list'),
    path('genres/<int:genre_id>/', GenreDetailView.as_view(), name='genre-detail'),
    path('users/<int:user_id>/playlists/', UserPlaylistListView.as_view(), name='user-playlist-list'),
    path('users/<int:user_id>/playlists/<int:playlist_number>/', UserPlaylistDetailView.as_view(), name='user-playlist-detail'),
    path('users/<int:user_id>/playlists/<int:playlist_number>/songs/', UserPlaylistSongsView.as_view(), name='user-playlist-songs'),
    path('top-songs/', TopSongsView.as_view(), name='top-songs'),
    path('search/', SearchView.as_view(), name='search'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<int:user_id>/', UserDetailView.as_view(), name='user-detail'),
    path('listening-history/', ListeningHistoryView.as_view(), name='listening-history'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('auth/google/', GoogleAuthView.as_view(), name='google-auth'),
    path('auth/google/callback/', GoogleCallbackView.as_view(), name='google-callback'),
    path('users/<int:user_id>/likes/', UserLikesView.as_view(), name='user-likes'),
    path('users/<int:user_id>/listening_history/', UserListeningHistoryView.as_view(), name='user-history'),
    path('songs/random/', RandomSongsView.as_view(), name='random-songs'),
    path('import-songs/', ImportSongsView.as_view(), name='import-songs'),
    path('admin-playlists/', AdminPlaylistListView.as_view(), name='admin-playlist-list'),
    path('admin-playlists/<int:admin_playlist_id>/', AdminPlaylistDetailView.as_view(), name='admin-playlist-detail'),
    path('messages/', MessageListView.as_view(), name='message-list'),
    path('messages/read/', MessageReadView.as_view(), name='message-read'),
    path('friend-requests/', FriendRequestListView.as_view(), name='friend-request-list'),
    path('friend-requests/<int:request_id>/', FriendRequestDetailView.as_view(), name='friend-request-detail'),
    path('friend-requests/<int:request_id>/accept/', FriendRequestAcceptView.as_view(), name='friend-request-accept'),
    path('friend-requests/<int:request_id>/reject/', FriendRequestRejectView.as_view(), name='friend-request-reject'),
    path('users/<int:user_id>/friends/', FriendsListView.as_view(), name='user-friends'),
    path('verify-password/', VerifyPasswordView.as_view(), name='verify-password'),
]
