/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "OpenSearchSetupV2": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SearchIndexer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SpotifyMedia": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SpotifyTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SpotifyUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "SpotifyUserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}